version: '3'
services:
  prisma-membership:
    container_name: prisma-membership
    platform: linux/amd64
    image:  mysql
    restart: always
    ports:
      - '5435:3306'
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - prisma-membership-volume:/var/lib/mysql

volumes:
  prisma-membership-volume:
